using System;

namespace RajFabAPI.DTOs
{
    public class EstablishmentRegistrationDto
    {
        // Primary identifier (optional when creating; present when reading)
        public Guid? Id { get; set; }

        // Business registration number (generated by service)
        public string? EstablishmentRegistrationId { get; set; }

        // FK to the EstablishmentDetail row created for this registration (optional)
        public Guid? EstablishmentDetailId { get; set; }

        // Workflow / processing status (e.g. "Pending", "Approved", "Rejected")
        public string? Status { get; set; } 
        public string? ApplicationId { get; set; }

        public bool AutoRenewal { get; set; }

        public string? Place { get; set; }
        public decimal Amount { get; set; }
        public string? Signature { get; set; }
        public DateTime? Date { get; set; }
        public string ApplicationRegistrationNumber { get; set; }
        public string ApplicationPDFUrl { get; set; }
        public string? CertificatePDFUrl { get; set; }
        public string? ObjectionLetterUrl { get; set; }

        // Audit
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string OccupierIdProof { get; set; }
        public string PartnershipDeed { get; set; }
        public string ManagerIdProof { get; set; }
        public string LoadSanctionCopy { get; set; }
    }
    public class CertificateRequestDto
    {
        public string Remarks { get; set; }
    }
    public class EstablishmentCertificatePdfRequestDto : CreateEstablishmentRegistrationDto
    {
        public string ApplicationId { get; set; }
        public string ApplicationRegistrationNumber { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string EstablishmentName { get; set; }
        public string NatureOfWork { get; set; }
        public string EstablishmentType { get; set; }

        public int? DirectEmployees { get; set; }
        public int? ContractorEmployees { get; set; }
        public ContractorDetailDto? ContractorDetails { get; set; }
        public int? InterStateWorkers { get; set; }

        public string FactoryManufacturingType { get; set; }
        public string FactoryManufacturingDetail { get; set; }
        public string FactorySituation { get; set; }
        public string FactoryAddress { get; set; }

        public string EmployerName { get; set; }
        public string EmployerDesignation { get; set; }
        public string EmployerAddress { get; set; }

        public string ManagerName { get; set; }
        public string ManagerDesignation { get; set; }
        public string ManagerAddress { get; set; }

        public int? MaxWorkers { get; set; }
        public int? NumberOfContractors { get; set; }
        public string Remarks { get; set; }
        public decimal? RegistrationFeesPaid { get; set; }

        public string DeclarationPlace { get; set; }
        public string SignatureBase64 { get; set; } // optional scanned signature
    }
}