export const establishmentDefaultData = {
    establishmentDetails: {
        id: "EST-001",
        linNumber: "LIN123456789",
        brnNumber: "0858250000000219",
        panNumber: "ABCDE1234F",
        name: "ABC Manufacturing Pvt Ltd",
        addressLine1: "Plot No. 45, Industrial Area",
        addressLine2: "Phase II",
        districtId: "D001",
        districtName: "Central District",
        subDivisionId: "SD001",
        subDivisionName: "North Sub Division",
        tehsilId: "T001",
        tehsilName: "Metro Tehsil",
        area: "Industrial Zone",
        pincode: "110001",
        email: "info@abcmanufacturing.com",
        telephone: "1145678901",
        mobile: "9876543210",
        totalNumberOfEmployee: 25,
        totalNumberOfContractEmployee: 40,
        totalNumberOfInterstateWorker: 25,
    },

    factory: {
        manufacturingType: "manufacture",
        manufacturingDetail: "Non Chemical", 
        factorySituation: "Located in designated industrial area",
        addressLine1: "Plot No. 45, Industrial Area",
        addressLine2: "Phase II",
        districtId: "D001",
        districtName: "Central District",
        subDivisionId: "SD001",
        subDivisionName: "North Sub Division",
        tehsilId: "T001",
        tehsilName: "Metro Tehsil",
        area: "Industrial Zone",
        pincode: "110001",
        email: "factory@abcmanufacturing.com",
        telephone: "1145678902",
        mobile: "9876543211",
        numberOfWorker: 25,
        sanctionedLoad: 100,
        sanctionedLoadUnit: "HP",
        ownershipType: "",
        ownershipSector: "Private",
        activityAsPerNIC: "Manufacture of motor vehicle parts",
        nicCodeDetail: "NIC-29309",
        identificationOfEstablishment: "Near Metro Station Phase II",

        employerDetail: {
            relationType: "father",
            relativeName: "Ramesh Verma",
            typeOfEmployer: "owner",
            id: "EMP-001",
            name: "Rajesh Sharma",
            role: "Employer",
            designation: "Managing Director",
            addressLine1: "12, Green Park",
            addressLine2: "Block A",
            district: "Central District",
            tehsil: "Metro Tehsil",
            area: "Green Park",
            pincode: "110016",
            email: "rajesh.sharma@abcmanufacturing.com",
            telephone: "1122334455",
            mobile: "9812345678",
        },

        managerDetail: {
            relationType: "father",
            relativeName: "Ramesh Verma",
            id: "MGR-001",
            name: "Anita Verma",
            role: "Manager",
            typeOfEmployer: "manager",
            designation: "Plant Manager",
            addressLine1: "34, Sunrise Apartments",
            addressLine2: "Sector 10",
            district: "Central District",
            tehsil: "Metro Tehsil",
            area: "Sector 10",
            pincode: "110075",
            email: "anita.verma@abcmanufacturing.com",
            telephone: "1199887766",
            mobile: "9823456789",
        },
    },

    beediCigarWorks: {
        manufacturingType: "",
        manufacturingDetail: "",
        situation: "",
        divisionId: "",
        districtId: "",
        areaId: "",
        address: "",
        pincode: "",
        employerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        managerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        maxNumberOfWorkerAnyDay: 0,
        numberOfHomeWorker: 0,
    },

    motorTransportService: {
        natureOfService: "",
        situation: "",
        divisionId: "",
        districtId: "",
        areaId: "",
        address: "",
        pincode: "",
        employerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        managerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        maxNumberOfWorkerDuringRegistation: 0,
        totalNumberOfVehicles: 0,
    },

    buildingAndConstructionWork: {
        workType: "",
        probablePeriodOfCommencementOfWork: "",
        expectedPeriodOfCommencementOfWork: "",
        localAuthorityApprovalDetail: "",
        dateOfCompletion: "",
    },

    newsPaperEstablishment: {
        name: "",
        divisionId: "",
        districtId: "",
        areaId: "",
        address: "",
        pincode: "",
        employerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        managerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        maxNumberOfWorkerAnyDay: 0,
        dateOfCompletion: "",
    },

    audioVisualWork: {
        name: "",
        divisionId: "",
        districtId: "",
        areaId: "",
        address: "",
        pincode: "",
        employerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        managerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        maxNumberOfWorkerAnyDay: 0,
        dateOfCompletion: "",
    },

    plantation: {
        name: "",
        divisionId: "",
        districtId: "",
        areaId: "",
        address: "",
        pincode: "",
        employerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        managerDetail: {
            role: "",
            name: "",
            designation: "",
            divisionId: "",
            districtId: "",
            areaId: "",
            address: "",
            pincode: "",
        },
        maxNumberOfWorkerAnyDay: 0,
        dateOfCompletion: "",
    },

    mainOwnerDetail: {
        id: "OWN-001",
        name: "Rajesh Sharma",
        role: "Owner",
        designation: "Director",
        typeOfEmployer: "owner",
        relationType: "father",
        relativeName: "Mahesh Sharma",
        addressLine1: "12, Green Park",
        addressLine2: "Block A",
        district: "Central District",
        tehsil: "Metro Tehsil",
        area: "Green Park",
        pincode: "110016",
        email: "owner@abcmanufacturing.com",
        telephone: "1122334455",
        mobile: "9812345678",
    },

    managerOrAgentDetail: {
        id: "AGT-001",
        name: "Anita Verma",
        role: "Manager",
        designation: "Authorized Signatory",
        typeOfEmployer: "manager",
        relationType: "father",
        relativeName: "Ramesh Verma",
        addressLine1: "34, Sunrise Apartments",
        addressLine2: "Sector 10",
        district: "Central District",
        tehsil: "Metro Tehsil",
        area: "Sector 10",
        pincode: "110075",
        email: "agent@abcmanufacturing.com",
        telephone: "1199887766",
        mobile: "9823456789",
    },

    contractorDetail: [
        {
            id: "CON-001",
            name: "Rakesh Kumar",
            companyName: "RK Contractors",
            addressLine1: "89, Business Park",
            addressLine2: "Tower B",
            district: "Central District",
            tehsil: "Metro Tehsil",
            area: "Business Hub",
            pincode: "110020",
            email: "contact@rkcontractors.com",
            mobile: "9898989898",
            maxContractWorkerCountFemale: 20,
            maxContractWorkerCountMale: 20,
            maxContractWorkerCountTransgender: 20,
            dateOfCommencement: "15/03/2026",
            dateOfCompletion: "19/03/2026",
            nameOfWork: "test data"
        },
    ],

    occupierIdProof: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
    partnershipDeed: "http://localhost:5000/documents/1ab16e04-bbb4-4026-88b8-b718792ff351_establishment-certificate (1).pdf",
    managerIdProof: "http://localhost:5000/documents/fe611cd5-3411-45f2-8945-7938f2c3c473_IMG-20251114-WA0003 (1).jpg",
    loadSanctionCopy: "http://localhost:5000/documents/fe611cd5-3411-45f2-8945-7938f2c3c473_IMG-20251114-WA0003 (1).jpg",

    place: "New Delhi",
    date: "2026-06-30",
    autoRenewal: false,
    signature: "https://dummyimage.com/150x50/000/fff&text=Signature",
    applicationRegistrationNumber: "APP-REG-2026-0001",
    sameAsFactoryManager:false,
    sameAsFactoryEmployer:false
}

export const mapApprovalDefaultData = {
    // ===== OCCUPIER DETAILS =====
    occupierName: "Ramesh Kumar Sharma",
    occupierFatherName: "Mahesh Chand Sharma",
    occupierOfficePlot: "Plot No. 21",
    occupierOfficeStreet: "Industrial Area Phase II",
    occupierOfficeTown: "Jaipur",
    occupierOfficeDistrict: "Jaipur",
    occupierOfficeArea: "Sitapura",
    occupierOfficePin: "302022",
    occupierResidentialPlot: "House No. 45",
    occupierResidentialStreet: "Shastri Nagar",
    occupierResidentialTown: "Jaipur",
    occupierResidentialDistrict: "Jaipur",
    occupierResidentialArea: "Shastri Nagar",
    occupierResidentialPin: "302016",
    occupierMobile: "9876543210",
    occupierEmail: "ramesh.sharma@example.com",

    // ===== FACTORY DETAILS =====
    factoryName: "RajFab Engineering Works",
    factorySituation: "Industrial Area, Sitapura",
    factoryPlotNo: "Plot No. C-18",
    divisionId: "2B8578BE-1D0C-4C29-AC49-FF76B7A258BC",
    districtId: "47C42DD0-4293-4255-9966-8A26FDF662C2",
    areaId: "8BB05CF0-9DDB-4CA2-8014-1365CB0B69C0",
    factoryPin: "302022",
    contactNo: "01412987654",
    email: "info@rajfab.com",
    website: "https://www.rajfab.com",

    // ===== PLANT & PROCESS =====
    plantParticulars: "CNC Machines, Lathe Machines, Hydraulic Press",
    productName: "Steel Fabricated Components",
    manufacturingProcess: "Cutting, Welding, Machining and Finishing",
    maxWorkerMale: 45,
    maxWorkerFemale: 15,
    areaFactoryPremises: "2500 Sq. Meters",

    // ===== COMMON PREMISES =====
    isCommonPremises: true,
    commonFactoryCount: 2,
    premiseOwnerName: "Suresh Industries Pvt. Ltd.",
    premiseOwnerContactNo: "9823456789",
    premiseOwnerAddressPlotNo: "Plot No. 12",
    premiseOwnerAddressStreet: "Industrial Area Phase I",
    premiseOwnerAddressCity: "Jaipur",
    premiseOwnerAddressDistrict: "Jaipur",
    premiseOwnerAddressState: "Rajasthan",
    premiseOwnerAddressPincode: "302022",

    // ===== DECLARATION =====
    place: "Jaipur",
    date: "2026-01-28",

    // ===== RAW MATERIALS =====
    rawMaterials: [
        {
            materialName: "Mild Steel Sheets",
            maxStorageQuantity: "50 MT",
            name: "MS Sheets",
            quantity: "50"
        },
        {
            materialName: "Iron Rods",
            maxStorageQuantity: "30 MT",
            name: "Iron Rods",
            quantity: "30"
        }
    ],

    // ===== INTERMEDIATE PRODUCTS =====
    intermediateProducts: [
        {
            productName: "Cut Steel Frames",
            maxStorageQuantity: "20 MT",
            name: "Steel Frames",
            quantity: "20"
        }
    ],

    // ===== FINAL PRODUCTS =====
    finalProducts: [
        {
            productName: "Fabricated Steel Components",
            maxStorageQuantity: "25 MT",
            name: "Steel Components",
            quantity: "25"
        }
    ],

    // ===== CHEMICALS =====
    chemicals: [
        {
            tradeName: "RustGuard X",
            chemicalName: "Anti-Corrosion Oil",
            maxStorageQuantity: "500 Liters"
        },
        {
            tradeName: "WeldFlux Pro",
            chemicalName: "Welding Flux",
            maxStorageQuantity: "200 Kg"
        }
    ],
    file: {
        landOwnershipDocumentUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        approvedLandPlanUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        manufacturingProcessDescriptionUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        processFlowChartUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        rawMaterialsListUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        hazardousProcessesListUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        emergencyPlanUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        safetyHealthPolicyUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        factoryPlanDrawingUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        safetyPolicyApplicableUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        occupierPhotoIdProofUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
        occupierAddressProofUrl: "http://localhost:5000/documents/72443a0b-e7f5-4477-8b9a-5b617770232c_establishment-certificate (3).pdf",
    }
};

export const BoilerRegistrationDefaultData = {
    applicationNo: "2026/2/BR/29192",

    /* ===== UPDATED GENERAL INFORMATION ===== */
    generalInformation: {
        factoryName: "Shivam Rice Mills Pvt. Ltd.",
        factoryRegistrationNumber: "BR-IND-55678",
        addressLine1: "Plot No. 18, Industrial Area",
        addressLine2: "Near NH-31 Bypass",
        districtId: "01",
        districtName: "Patna",
        subDivisionId: "001",
        subDivisionName: "Patna Sadar",
        tehsilId: "T01",
        tehsilName: "Phulwari Sharif",
        area: "Urban Industrial",
        pinCode: "800001",
        mobile: "9876543210",
        telephone: "6122244668",
        email: "info@shivamricemills.com",
        erectionTypeId: "1",
    },

    ownerInformation: {
        ownerName: "Amit Kumar Singh",
        designation: "Managing Director",
        role: "Owner",
        typeOfEmployer: "Proprietor",
        relationType: "S/O",
        relativeName: "Rajendra Singh",
        addressLine1: "House No. 221, Kankarbagh",
        addressLine2: "Near Rajendra Nagar Terminal",
        districtName: "Patna",
        subDivisionName: "Patna Sadar",
        tehsilName: "Sampatchak",
        area: "Urban",
        pinCode: "800020",
        mobile: "9123456780",
        telephone: "6122233554",
        email: "amit.singh@email.com",
    },

    makerInformation: {
        makerName: "Thermax Boilers Ltd.",
        designation: "Chief Engineer",
        role: "Manufacturer",
        typeOfEmployer: "Company",
        relationType: "N/A",
        relativeName: "N/A",
        addressLine1: "Boiler Division, Industrial Estate",
        addressLine2: "Phase III, MIDC Area",
        districtName: "Pune",
        district: "Pune",
        subDivisionName: "Haveli",
        tehsilName: "Mulshi",
        area: "Industrial",
        pinCode: "411019",
        mobile: "9988776655",
        telephone: "2044556677",
        email: "support@thermaxglobal.com",
    },

    boilerDetails: {
        makerNumber: "THX-BOIL-2022-7788",
        makerNameAndAddress: "Thermax Boilers Ltd., Pune, Maharashtra",
        yearOfMake: "2022",
        heatingSurfaceArea: "320",

        evaporationCapacity: "5000",
        evaporationUnit: "Kg/hr",

        intendedWorkingPressure: "14",
        pressureUnit: "Kg/cm2",

        boilerType: "Water Tube Boiler",
        boilerCategory: "Industrial",

        superheater: "Yes",
        superheaterOutletTemp: "350",

        economiser: "Yes",
        economiserOutletTemp: "190",

        furnaceType: "Coal Fired",
    },

    documents: {
        drawings: "drawings_layout.pdf",
        specification: "technical_specification.pdf",
        formI_B_C: "form_I_B_C_signed.pdf",
        formI_D: "form_I_D_signed.pdf",
        formI_E: "form_I_E_signed.pdf",
        formIV_A: "form_IV_A_certificate.pdf",
        formV_A: "form_V_A_certificate.pdf",
        testCertificates: "hydro_test_certificate.pdf",
        weldRepairCharts: "weld_repair_chart.pdf",
        pipesCertificates: "pipes_test_certificate.pdf",
        tubesCertificates: "tubes_test_certificate.pdf",
        castingCertificate: "casting_certificate.pdf",
        forgingCertificate: "forging_certificate.pdf",
        headersCertificate: "headers_certificate.pdf",
        dishedEndsInspection: "dished_ends_report.pdf",
        boilerAttendantCertificate: "boiler_attendant_license.pdf",
        boilerOperationEngineerCertificate: "boiler_operation_engineer_license.pdf",
    },
}
